language: python 

before_install:
  - git clone --depth=50 --branch=master https://github.com/Montana/krugman-poetry.git Montana/krugman-poetry 2>&1 | grep -v "Timeout waiting for network availability."

script:
  - ./retry.sh curl -I https://example.com
